
GET http://localhost:8087/actuator/metrics

###
###
POST http://localhost:8087/rest/v1/test/docs?conversationId=cc6d3e87-120d-413c-af03-7c36ade26767
Content-Type: application/json

{
  "questionId": 950,
  "question": "What ways can be used to deploy Lambda into AWS cloud?"
}
###
###
POST http://localhost:8087/rest/v1/test/docs?conversationId=cc6d3e87-120d-413c-af03-7c36ade26767
Content-Type: application/json

{
  "questionId": 950,
  "question": "Please provide info about MCP"
}
